In [1]:
import numpy as np
import tensorflow as tf

In [2]:
def RNNCell(X, prev, parameters):
    
    Wax = parameters["Wax"]
    Waa = parameters["Waa"]
    Wya = parameters["Wya"]
    ba = parameters["ba"]
    by = parameters["by"]
    
    a_next = tf.tanh(tf.matmul(Waa, a_prev) + tf.matmul(Wax, X) + ba)
    
    yt_pred = tf.softmax(tf.matmul(Wya, a_next) + by)
    
    return a_next, yt_pred    

In [3]:
parameters = {
    'Waa' : tf.get_variable('Waa', shape = [5,5], dtype = tf.float32),
    'Wax' : tf.get_variable('Wax', shape = [5,3], dtype = tf.float32),
    'Wya' : tf.get_variable('Wya', shape = [2,5], dtype = tf.float32),
    'ba' : tf.get_variable('ba', shape = [5,1], dtype = tf.float32),
    'by' : tf.get_variable('by', shape = [2,1], dtype = tf.float32)
}

In [4]:
init = tf.global_variables_initializer()

In [33]:
with tf.Session() as sess:
    init.run()


[[-0.40301982  0.6819979   0.06510961 -0.5896457  -0.25082833]
 [-0.04550046  0.25146163 -0.54693234 -0.58607143  0.31844592]
 [ 0.45459235 -0.05293065 -0.0686183  -0.14816034 -0.05389559]
 [-0.6360853  -0.7089565  -0.6022134   0.39960074 -0.7456988 ]
 [-0.7450833  -0.14563322  0.13371903 -0.63190174 -0.47995013]]
[[-0.77579284  0.5672038  -0.62237686]
 [ 0.03602374 -0.39056194 -0.42316315]
 [-0.4479391   0.7189478   0.53354937]
 [-0.14175647 -0.01678884  0.4910124 ]
 [-0.6950917  -0.81192523 -0.6215318 ]]
[[ 0.24114323  0.08910489  0.54834735  0.6775062  -0.1953147 ]
 [ 0.28729403 -0.61403096  0.40718567  0.06877124  0.01660305]]
[[-0.06922293]
 [-0.09777236]
 [ 0.42173862]
 [-0.09464121]
 [ 0.65361667]]
[[ 0.43749774]
 [-0.31243658]]
